stages:   
   - quality
   - build
   - unit_test
   - active_tests

variables:
  GIT_STRATEGY: clone
  TIMEOUT: 10m

styleCheck:
   stage: quality
   script:
      - make style

game-server:
   stage: build
   tags:
      - "docker"
   script:
      make gameServer

test-server:
   stage: active_tests
   tags:
      - "docker"
   script:
      make coverage

build-docker:
   stage: build
   tags:
      - "docker"
   script:
      - make docker
   allow_failure: true
